### ISSUE TITLE
Reconsider `SOTGroupsInformation()`

### ISSUE THREAD

**Issue by fingolfin** [xpan-eileen/sotgrps#22]
I am not sure what the point of `SOTGroupsInformation()` is. Right now I got this output:
```
gap> SOTGroupsInformation();
AllSOTGroups(#) constructs all groups of order # up to isomorphism, where \
# factorises into at most 4 primes or # = p^4q, where p and q are distinct\
 primes.
```

First off, the use of `#` greatly confused me, as this usually starts a comment and by chance it started a line here. Anyway, I think it is intended to be a placeholder. OK, fine, but then this basically just describes `AllSOTGroups`. But if I already know about `SOTGroupsInformation`, wouldn't I also know about `AllSOTGroups`? And if so, I can just enter `?AllSOTGroups` to get information about it.

So I am not sure what the purpose of this variant of `SOTGroupsInformation`. My instinct says to remove it. Or else come up with something more useful and print that. Like, perhaps it could print explicitly the list of factorizations, or so. But in the end I think this makes more sense in the manual?

**Comment by xpan-eileen** [comment]
I agree with you, I have now got rid of it.
