### ISSUE TITLE
Transfer this repo to `gap-packages` ?

### ISSUE THREAD

**Issue by fingolfin** [xpan-eileen/sotgrps#23]
Let's settle this one way or another: would you be open to transfer this package to the `gap-packages` GitHub organization?

Pro:
- GAP maintainers like me then can admin the repository, thus helping with maintaining the package (so if you at some point don't have time to take care of, say, a simple bug fix, others can help out)
- in particular I can then do things like set up the website for the package etc.
- and, if you give permission, we can even make releases for you (if you want that / are willing to live with that, we'd add "The GAP team" to the list of package maintainers in `PackageInfo.g`
- ... in general this ensures long term availability and support for the package

Con:
- you give up some control over the package (though we are very respectful; and anyway, you can "take back" exclusive control at any time should you want to
- ?

Let me emphasise that this is not *necessary* at all, so please don't feel pressured into doing it. However, in my experience it simplifies things quite a bit, at least on our side (and many package authors are actually relieved that they don't have to e.g. remember all the steps to make a clean package release).

The decision is 100% yours, but it should be made now, so we can decide how to proceed with setting up a website, making a release etc.

**Comment by xpan-eileen** [comment]
Thanks Max. Yes, I think it would be beneficial to do the transfer. Let's do it. Thanks.
